kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-default-web3
  template:
    metadata:
      labels:
        app: deployment-default-web3
    spec:
      containers:
      - image: nginx
        name: web
        volumeMounts:
        - mountPath: /test
          name: vol1
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: myclaim3
